# Pandas

In [1]:
import numpy as np
import pandas as pd

C:\Users\PC 10\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
print(pd.__version__)

3.0.2

In [181]:
# 然后点击Kernel--restart Kernel，然后再从import来一遍就能看到更新的版本了
!pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\pc 10\anaconda3\lib\site-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc 10\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc 10\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pc 10\anaconda3\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pc 10\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.7 MB 3.2 MB/s eta 0:00:04
   --------- ------------------------------ 2.2/9.7 MB 23.5 MB/s eta 0:00:01
   ---------------------- ----------------- 5.6/9.7 MB 39.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.8/9.7 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 44.5 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
Successfully installed pandas-3.0.2

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\PC 10\anaconda3\Lib\site-packages\~andas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\PC 10\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.32.0 requires pandas<3,>=1.3.0, but you have pandas 3.0.2 which is incompatible.

# Creating Series

# From list

In [3]:
list=[10,20,30,40,50]
label=['a','b','c','d','e']
s1=pd.Series(list,index=label)
print(s1)

a    10
b    20
c    30
d    40
e    50
dtype: int64

# From 1D

In [5]:
narr=np.array([10,20,30,40,50])
s2=pd.Series(narr,index=label)
print(s2)

a    10
b    20
c    30
d    40
e    50
dtype: int32

# From dictionary

In [7]:
# 字典必须在创建的时候就定义key，不能像list和1维数组那样用label定义
dict={'a':10,'b':20,'c':30,'d':40,'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [8]:
s3.dtypes

dtype('int64')

In [9]:
s3.info

<bound method Series.info of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [10]:
s3.size

5

In [11]:
#转为float
s3.astype(float)

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float64

In [12]:
#字典的drop需要删除的是key，其他直接drop索引
s3.drop('b')

a    10
c    30
d    40
e    50
dtype: int64

# Creating DataFrame

# From list of lists

In [13]:
# 注意columns需要加是复数s！！！
list=[[1,2],[3,4],[5,6]]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col_1','col_2'])
print(df1)

   col_1  col_2
a      1      2
b      3      4
c      5      6

# From 2D ndarray

In [14]:
ndarr=np.array([[1,2],[3,4],[5,6]])
df2=pd.DataFrame(ndarr,index=['a','b','c'],columns=['col_1','col_2'])
print(df2)

   col_1  col_2
a      1      2
b      3      4
c      5      6

# From dictionary

In [15]:
df3=pd.DataFrame({'R1':[1,2,3],'R2':[4,5,6]},index=['a','b','c'])
print(df3)

   R1  R2
a   1   4
b   2   5
c   3   6

In [16]:
df3.dtypes

R1    int64
R2    int64
dtype: object

In [17]:
df3.info

<bound method DataFrame.info of    R1  R2
a   1   4
b   2   5
c   3   6>

In [111]:
df3['R1'].dtypes

dtype('int64')

In [113]:
df3.shape

(3, 2)

In [18]:
df3.head(2)

   R1  R2
a   1   4
b   2   5

In [19]:
df3.tail(2)

   R1  R2
b   2   5
c   3   6

In [20]:
df3.drop('b',axis=0)

   R1  R2
a   1   4
c   3   6

In [21]:
df3.drop('R1',axis=1)

   R2
a   4
b   5
c   6

# Indexing Data in a Series

In [22]:
dict={'a':10,'b':20,'c':30,'d':40,'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [23]:
s3['b']

20

In [24]:
s3.iloc[1]

20

In [25]:
s3[['a','c']]

a    10
c    30
dtype: int64

In [29]:
# iloc() 是索引位置
# dictionary索引是两个[]
s3.iloc[[1,2]]

b    20
c    30
dtype: int64

In [27]:
s3[s3>20]

c    30
d    40
e    50
dtype: int64

# Indexing in a DataFrame

In [28]:
list=[[1,2],[3,4],[5,6]]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col_1','col_2'])
print(df1)

   col_1  col_2
a      1      2
b      3      4
c      5      6

In [170]:
# 一个中括号
df1['col_1']

a    1
b    3
c    5
Name: col_1, dtype: int64

In [30]:
# 两个中括号
df1[['col_1','col_2']]

   col_1  col_2
a      1      2
b      3      4
c      5      6

# loc

In [184]:
df1.loc['a']

col_1    1
col_2    2
Name: a, dtype: int64

# iloc

In [188]:
df1.iloc[2]

col_1    5
col_2    6
Name: c, dtype: int64

In [191]:
df1.iloc[1,1]

np.int64(4)

# Arithmetic

In [33]:
# Exercise
sales=pd.DataFrame({'Month':['Jan','Feb','Mar','Apr','May','Jun'],
                   'Revenue':[50000,55000,48000,62000,58000,61000],
                    'Expenses':[35000,38000,34000,41000,39000,40000]})
sales

  Month  Revenue  Expenses
0   Jan    50000     35000
1   Feb    55000     38000
2   Mar    48000     34000
3   Apr    62000     41000
4   May    58000     39000
5   Jun    61000     40000

In [202]:
# Find the first 2 row of the data i.e. month,revenue,expenses
sales.head(2)

  Month  Revenue  Expenses
0   Jan    50000     35000
1   Feb    55000     38000

In [236]:
# Find the first 3 months of Revenue
sales['Revenue'].iloc[:3]
# sales['Revenue'].head(3)

0    50000
1    55000
2    48000
Name: Revenue, dtype: int64

In [230]:
# Find the last 2 month of expenses
sales['Expenses'].iloc[-2:]
# sales['Revenue'].tail(2)

4    39000
5    40000
Name: Expenses, dtype: int64

In [34]:
profit=sales['Revenue']-sales['Expenses']
profit

0    15000
1    17000
2    14000
3    21000
4    19000
5    21000
dtype: int64

In [35]:
sales['Revenue']*sales['Expenses']

0    1750000000
1    2090000000
2    1632000000
3    2542000000
4    2262000000
5    2440000000
dtype: int64

In [36]:
sales['Revenue']/sales['Expenses']

0    1.428571
1    1.447368
2    1.411765
3    1.512195
4    1.487179
5    1.525000
dtype: float64

In [37]:
sales['Revenue']+sales['Expenses']

0     85000
1     93000
2     82000
3    103000
4     97000
5    101000
dtype: int64

In [38]:
sales['Revenue']*2

0    100000
1    110000
2     96000
3    124000
4    116000
5    122000
Name: Revenue, dtype: int64

In [40]:
print(sales)
print(profit)

  Month  Revenue  Expenses
0   Jan    50000     35000
1   Feb    55000     38000
2   Mar    48000     34000
3   Apr    62000     41000
4   May    58000     39000
5   Jun    61000     40000
0    15000
1    17000
2    14000
3    21000
4    19000
5    21000
dtype: int64

In [41]:
sales['profit']=sales['Revenue']-sales['Expenses']
print(sales)

  Month  Revenue  Expenses  profit
0   Jan    50000     35000   15000
1   Feb    55000     38000   17000
2   Mar    48000     34000   14000
3   Apr    62000     41000   21000
4   May    58000     39000   19000
5   Jun    61000     40000   21000

In [51]:
sales[['Expenses' ,'Revenue']]

   Expenses  Revenue
0     35000    50000
1     38000    55000
2     34000    48000
3     41000    62000
4     39000    58000
5     40000    61000

# Duplicates in Labels

In [58]:
# 列名必须是单一的，不能重名
data={"A":[1,2,3],"B":[4,5,6],"A":[7,8,9]}
df=pd.DataFrame(data)
df

   A  B
0  7  4
1  8  5
2  9  6

In [60]:
# 行标签可以重名
data={"A":[1,2,3],"B":[4,5,6],"C":[7,8,9]}
df=pd.DataFrame(data,index=['a','b','a'])
df

   A  B  C
a  1  4  7
b  2  5  8
a  3  6  9

In [63]:
df.loc['a']

   A  B  C
a  1  4  7
a  3  6  9

In [64]:
df.loc['b']

A    2
B    5
C    8
Name: b, dtype: int64

In [67]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr,columns=['A','B','A'])
df

   A  B  A
0  1  2  3
1  4  5  6
2  7  8  9

In [71]:
# 如果是A就是dataframe，如果是B就是Series
df['A']

   A  A
0  1  3
1  4  6
2  7  9

# Descriptive Statistics

In [72]:
df.describe()

         A    B    A
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [73]:
# 给的是列的mean
df.mean()

A    4.0
B    5.0
A    6.0
dtype: float64

In [74]:
df.median()

A    4.0
B    5.0
A    6.0
dtype: float64

In [79]:
arr=np.array([[1,2,3],[2,8,6],[2,8,8]])
df=pd.DataFrame(arr,columns=['A','B','A'])
df

   A  B  A
0  1  2  3
1  2  8  6
2  2  8  8

In [80]:
df.mode()

     A    B  A
0  2.0  8.0  3
1  NaN  NaN  6
2  NaN  NaN  8

In [76]:
df.std()

A    3.0
B    3.0
A    3.0
dtype: float64

In [81]:
df.var()

A     0.333333
B    12.000000
A     6.333333
dtype: float64

In [82]:
df.min()

A    1
B    2
A    3
dtype: int32

In [83]:
df.max()

A    2
B    8
A    8
dtype: int32

In [84]:
df.count()

A    3
B    3
A    3
dtype: int64

In [87]:
df['B'].unique()

array([2, 8])

# function application and mapping

In [92]:
# 可以直接用series计算，不用转为dataframe
series=pd.Series([1,2,3,4,5])
np.sqrt(series)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [95]:
dict={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(dict)
np.square(df)

   A   B
0  1  16
1  4  25
2  9  36

# apply

In [96]:
series=pd.Series([1,2,3,4,5])
series.apply(np.sqrt)

# np.sqrt(series)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [98]:
def categorize(x):
    if x >= 5:
        return "high"
    else:
        return"low"

In [112]:
# apply+function 为什么不能用于行？
df['B'].apply(categorize)

0     low
1    high
2    high
Name: B, dtype: object

In [111]:
df.apply(sum,axis=0)

A     6
B    15
dtype: int64

# map()

In [117]:
dict={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(dict)
df.map(np.square)
# np.square(df)  # 一样的结果

   A   B
0  1  16
1  4  25
2  9  36

In [118]:
df['B'].apply(categorize)

0     low
1    high
2    high
Name: B, dtype: object

In [119]:
df['B'].map(categorize)

0     low
1    high
2    high
Name: B, dtype: object

In [125]:
df=pd.DataFrame({'Month':['Jan','Feb','Mar','Apr'],
                  'Rev':[230,300,400,500]
})
df

  Month  Rev
0   Jan  230
1   Feb  300
2   Mar  400
3   Apr  500

In [130]:
df['Month'].map({'Jan':1,'Mar':99,"Mar":2,"Apr":4})

0    1.0
1    NaN
2    2.0
3    4.0
Name: Month, dtype: float64

In [134]:
dict={'A':[1,2,3],'B':[4,5,6]}
df=pd.DataFrame(dict)
df.apply(sum,axis=1)  # 但是map不行，apply 和map的区别需要特别注意

0    5
1    7
2    9
dtype: int64

# Pivot Tables and Cross Tabulations

# Pivot Tables

In [146]:
data={
    'City':['KL','Selongor','Ipoh','Kuching','KL','KL'],
    'Category':['A','A','B','B','B','B'],
    'Sales':[2000,3000,4000,5000,3000,1000]
}

df=pd.DataFrame(data)
df

       City Category  Sales
0        KL        A   2000
1  Selongor        A   3000
2      Ipoh        B   4000
3   Kuching        B   5000
4        KL        B   3000
5        KL        B   1000

In [151]:
# Default aggfunc=mean
pd.pivot_table(df,values='Sales',index='Category',columns='City')

City        Ipoh      KL  Kuching  Selongor
Category
A            NaN  2000.0      NaN    3000.0
B         4000.0  2000.0   5000.0       NaN

In [150]:
pd.pivot_table(df,values='Sales',index='Category',columns='City',aggfunc='sum')

City        Ipoh      KL  Kuching  Selongor
Category
A            NaN  2000.0      NaN    3000.0
B         4000.0  4000.0   5000.0       NaN

# Cross Tabulations

In [157]:
pd.crosstab(df['City'],df['Category'])

Category  A  B
City
Ipoh      0  1
KL        1  2
Kuching   0  1
Selongor  1  0

# View and Copy

In [3]:
# Pandas 3.0 already remove the warning 
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})

# create a view
view=df[['A','B']]

# modify the view
view['A']=9999

print(df)
print("\n")
print(view)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


      A  B
0  9999  4
1  9999  5
2  9999  6