# Pandas

In [1]:
import numpy as np
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\PC03\AppData\Local\Temp\ipykernel_21732\1662815981.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\__init__.py", line 34, in <module>
    from pandas.compat import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 28, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 12, in <module>
    import pyarrow as pa
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\PC03\AppData\Local\Temp\ipykernel_21732\1662815981.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 28, in <module>
    from pandas._libs import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\PC03\AppData\Local\Temp\ipykernel_21732\1662815981.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 65, in <module>
    from pandas.core import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 22, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\PC03\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\PC03\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\PC03\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\PC03\AppData\Local\Temp\ipykernel_21732\1662815981.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 56, in <module>
    from pandas.core import (
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\PC03\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\PC03\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\PC03\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [3]:
print(pd.__version__)

3.0.2

In [27]:
# 然后点击Kernel--restart Kernel，然后再从import来一遍就能看到更新的版本了
!pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\pc03\anaconda3\lib\site-packages (2.3.3)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc03\anaconda3\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc03\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pc03\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\pc03\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.7 MB 2.9 MB/s eta 0:00:04
   -- ------------------------------------- 0.6/9.7 MB 7.9 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.7 MB 10.3 MB/s eta 0:00:01
   -------- ------------------------------- 2.2/9.7 MB 12.6 MB/s eta 0:00:01
   ------------- -------------------------- 3.3/9.7 MB 15.0 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.7 MB 17.7 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.7 MB 18.6 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/9.7 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 23.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 23.1 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
    Uninstalling pandas-2.3.3:
      Successfully uninstalled pandas-2.3.3
Successfully installed pandas-3.0.2

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\PC03\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.4.4 which is incompatible.
streamlit 1.32.0 requires pandas<3,>=1.3.0, but you have pandas 3.0.2 which is incompatible.

# Creating Series

# From list

In [34]:
list=[10,20,30,40,50]
label=['a','b','c','d','e']
s1=pd.Series(list,index=label)
print(s1)

a    10
b    20
c    30
d    40
e    50
dtype: int64

# From 1D

In [36]:
# 字典必须在创建的时候就定义key，不能像list和1维数组那样用label定义
narr=np.array([10,20,30,40,50])
s2=pd.Series(narr,index=label)
print(s2)

a    10
b    20
c    30
d    40
e    50
dtype: int64

# From dictionary

In [30]:
dict={'a':10,'b':20,'c':30,'d':40,'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [38]:
s3.dtypes

dtype('int64')

In [40]:
s3.info

<bound method Series.info of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [42]:
s3.size

5

In [48]:
#转为float
s3.astype(float)

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float64

In [63]:
#字典的drop需要删除的是key，其他直接drop索引
s3.drop('b')

a    10
c    30
d    40
e    50
dtype: int64

# Creating DataFrame

# From list of lists

In [77]:
# 注意columns需要加是复数s！！！
list=[[1,2],[3,4],[5,6]]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col_1','col_2'])
print(df1)

   col_1  col_2
a      1      2
b      3      4
c      5      6

# From 2D ndarray

In [79]:
ndarr=np.array([[1,2],[3,4],[5,6]])
df2=pd.DataFrame(ndarr,index=['a','b','c'],columns=['col_1','col_2'])
print(df2)

   col_1  col_2
a      1      2
b      3      4
c      5      6

# From dictionary

In [87]:
df3=pd.DataFrame({'R1':[1,2,3],'R2':[4,5,6]},index=['a','b','c'])
print(df3)

   R1  R2
a   1   4
b   2   5
c   3   6

In [92]:
df3.dtypes

R1    int64
R2    int64
dtype: object

In [94]:
df3.info

<bound method DataFrame.info of    R1  R2
a   1   4
b   2   5
c   3   6>

In [111]:
df3['R1'].dtypes

dtype('int64')

In [113]:
df3.shape

(3, 2)

In [121]:
df3.head(2)

   R1  R2
b   2   5
c   3   6

In [123]:
df3.tail(2)

   R1  R2
b   2   5
c   3   6

In [129]:
df3.drop('b',axis=0)

   R1  R2
a   1   4
c   3   6

In [133]:
df3.drop('R1',axis=1)

   R2
a   4
b   5
c   6

# Indexing Data in a Series

In [139]:
dict={'a':10,'b':20,'c':30,'d':40,'e':50}
s3=pd.Series(dict)
print(s3)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [141]:
s3['b']

np.int64(20)

In [143]:
s3.iloc[1]

np.int64(20)

In [151]:
s3[['a','c']]

a    10
c    30
dtype: int64

In [157]:
# iloc() 是索引位置
s3.iloc[[1,2]]

b    20
c    30
dtype: int64

In [160]:
s3[s3>20]

c    30
d    40
e    50
dtype: int64

# Indexing in a DataFrame

In [162]:
list=[[1,2],[3,4],[5,6]]
df1=pd.DataFrame(list,index=['a','b','c'],columns=['col_1','col_2'])
print(df1)

   col_1  col_2
a      1      2
b      3      4
c      5      6

In [170]:
# 一个中括号
df1['col_1']

a    1
b    3
c    5
Name: col_1, dtype: int64

In [168]:
# 两个中括号
df1[['col_1','col_2']]

   col_1  col_2
a      1      2
b      3      4
c      5      6

# loc

In [184]:
df1.loc['a']

col_1    1
col_2    2
Name: a, dtype: int64

# iloc

In [188]:
df1.iloc[2]

col_1    5
col_2    6
Name: c, dtype: int64

In [191]:
df1.iloc[1,1]

np.int64(4)

In [196]:
# Exercise
sales=pd.DataFrame({'Month':['Jan','Feb','Mar','Apr','May','Jun'],
                   'Revenue':[50000,55000,48000,62000,58000,61000],
                    'Expenses':[35000,38000,34000,41000,39000,40000]})
sales

  Month  Revenue  Expenses
0   Jan    50000     35000
1   Feb    55000     38000
2   Mar    48000     34000
3   Apr    62000     41000
4   May    58000     39000
5   Jun    61000     40000

In [202]:
# Find the first 2 row of the data i.e. month,revenue,expenses
sales.head(2)

  Month  Revenue  Expenses
0   Jan    50000     35000
1   Feb    55000     38000

In [236]:
# Find the first 3 months of Revenue
sales['Revenue'].iloc[:3]

0    50000
1    55000
2    48000
Name: Revenue, dtype: int64

In [230]:
# Find the last 2 month of expenses
sales['Expenses'].iloc[-2:]

4    39000
5    40000
Name: Expenses, dtype: int64